name: logger_builder
description: A toolkit for creating your own customizable and hierarchical loggers in Dart.
version: 0.2.0
repository: https://github.com/vi-k/logger_builder

topics:
  - debugging
  - logging

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
