name: logger_builder_examples
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  ansi_escape_codes: ^2.1.0
  logger_builder:
    path: ../../
  logging: ^1.3.0
  meta: ^1.18.1
  talker_logger: ^5.1.13
  vm_service: ^15.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
